algo_config:
  max_num_steps: 1
  use_safe_input: True
  use_learned_model: False

  soft_constrained: False
  slack_weight: 10000.0 # 0.0
  slack_tolerance: 1.0E-3 # 0.0

  # Verify CBF parameters
  # tolerance: 0.0
  tolerance: 0.05
  # num_points: 10
  num_points: 50

  hidden_dims: [256, 256]
  learning_rate: 0.001

  num_episodes: 1
  max_buffer_size: 1.0E+6
  train_batch_size: 64
  train_iterations: 200




task_config:
  ctrl_freq: 100
  pyb_freq: 1000

  # randomization
  inertial_prop: null
  randomized_inertial_prop: False
  inertial_prop_randomization_info: null

  #prior_prop: null
  prior_prop:
    pole_length: 0.4
    pole_mass: 0.12
    cart_mass: 0.8

  randomized_init: False
  init_state_randomization_info: null

  # state initialization
  init_state:
    init_x: -0.3
    init_x_dot: 0.0
    init_theta: 0.06
    init_theta_dot: -0.04

  # constraints
  # constraints:
  #   cartpole_input:
  #     low: -8.0
  #     high: 8.0

  constraints:
  - constraint_form: default_constraint
    constrained_variable: state
  - constraint_form: default_constraint
    constrained_variable: input
    upper_bounds:
      - 8.0
    lower_bounds:
      - -8.0   
