algo_config:
  max_num_steps: 250

  soft_constrained: True
  slack_weight: 10000.0 # 0.0
  slack_tolerance: 1.0E-3 # 0.0

  hidden_dims: [256, 256]
  learning_rate: 0.001

  num_episodes: 20
  max_buffer_size: 1.0E+6
  train_batch_size: 64
  train_iterations: 200




task_config:
  ctrl_freq: 100
  pyb_freq: 1000

  # randomization
  inertial_prop: null
  randomized_inertial_prop: False
  inertial_prop_randomization_info: null

  #prior_prop: null
  prior_prop:
    pole_length: 0.4
    pole_mass: 0.12
    cart_mass: 0.8

  randomized_init: True
  init_state_randomization_info:
    "init_x":
        "distrib": "uniform"
        "low": -1.0
        "high": 1.0
    "init_x_dot":
        "distrib": "uniform"
        "low": -0.5
        "high": 0.5
    "init_theta":
        "distrib": "uniform"
        "low": -0.1
        "high": 0.1
    "init_theta_dot":
        "distrib": "uniform"
        "low": -0.1
        "high": 0.1
  # constraints
  constraints:
  - constraint_form: default_constraint
    constrained_variable: state
  - constraint_form: default_constraint
    constrained_variable: input
    upper_bounds:
      - 8.0
    lower_bounds:
      - -8.0
